[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_program = "29pLxWzjvbCyj7gEBQFfzhnwMZT2bFvMbUbWRN1991Sf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/tom/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
